## AWS Host Wireguard Tunnel Configuration

[Interface]
# AWS site (local)
Address = 10.10.1.1/30
ListenPort = 51000
PostUp = wg set %i private-key /home/ec2-user/vpn/aws.key



[Peer]
# Proxmox site (remote)
PublicKey = <location to/pve/public/key>
AllowedIPs = 10.10.1.2/32, 192.168.1.0/24
Endpoint = 88.92.209.167:51000
PersistentKeepalive = 25