## AWS Wireguard Configuration

[Interface]
# AWS site
Address = 10.10.0.1/30
SaveConfig = true
ListenPort = 51000
PostUp = wg set %i private-key /home/ec2-user/vp/%i.key


[Peer]
# Proxmox site
PublicKey = <location to/pve/public/key>
AllowedIPs = 192.168.1.0/24
Endpoint = 78.92.209.167:51000
