## Proxmox WireGuard Configuration

[Interface]
# Proxmox site (local)
Address = 10.10.1.2/30
ListenPort = 51000

# Load private key from your home directory
PostUp = wg set %i private-key /home/collins/wireguard/%i.key
# Using PostUp keeps the private key out of this config file


[Peer]
# AWS site (remote)
PublicKey = <publicKey here>
AllowedIPs = 172.31.80.0/20
Endpoint = 13.220.207.236:51000
PersistentKeepalive = 25